# Generated by Django 4.2.8 on 2024-07-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
