# Generated by Django 4.2.8 on 2024-07-14 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('sender', 'receiver')},
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.interest')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='interest',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='timestamp',
        ),
    ]
