# Generated by Django 4.2.8 on 2024-07-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_interest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
